import json
from pathlib import Path

from core.messages import PROFILES


ROOT = Path(__file__).resolve().parents[1]
GENERATOR_LINE = "Generated by astrbot_plugin_ark_calendar·bushikq"


def test_every_render_template_includes_generator_credit():
    for name in ("calendar.html", "help.html", "history_schedule.html", "bilibili_dynamic.html", "recruitment.html"):
        assert GENERATOR_LINE in (ROOT / "templates" / name).read_text(encoding="utf-8")


def test_recruitment_content_is_larger_than_its_title_supporting_style():
    template = (ROOT / "templates" / "recruitment.html").read_text(encoding="utf-8")
    assert ".hero h1{margin:14px 0 5px;font-size:51px}" in template
    assert ".hero p{margin:0;color:#c5d0d2;font:20px Arial" in template
    assert ".combo span{padding:6px 10px" in template
    assert "font:800 24px Arial" in template
    assert ".op{display:flex;align-items:center" in template
    assert ".op-avatar{width:54px;height:54px" in template
    assert "font-size:21px" in template


def test_message_previews_cover_the_current_builtin_message_profiles():
    schema = json.loads((ROOT / "_conf_schema.json").read_text(encoding="utf-8"))
    items = schema["messages"]["items"]
    templates = items["custom_messages"]["template_schema"]
    for profile, preview_key in (("rhodes_catgirl", "rhodes_catgirl_preview"), ("plain", "plain_preview")):
        expected = "\n\n".join(
            f"【{templates[key]['name']}】\n{value}"
            for key, value in PROFILES[profile].items()
        )
        assert items[preview_key]["default"] == expected


def test_bilibili_config_order_and_video_delivery_description():
    schema = json.loads((ROOT / "_conf_schema.json").read_text(encoding="utf-8"))
    assert list(schema) == [
        "basic", "scheduled_report", "scheduled_birthday_greeting", "bilibili_dynamic",
        "cache_and_render", "messages", "admin_notification", "data_sources",
    ]
    items = schema["bilibili_dynamic"]["items"]
    assert list(items) == [
        "push_enabled", "target_sid_list", "check_interval_minutes", "push_types",
        "render_image_count_threshold", "use_forward_on_qq", "list_default_count", "rsshub_base_url",
    ]
    assert "不下载或发送视频文件" in items["push_types"]["hint"]
    render_items = schema["cache_and_render"]["items"]
    assert "公招图和B站动态图" in render_items["render_device_scale_factor_level"]["hint"]
    assert "公招图和B站动态图始终使用 PNG" in render_items["render_image_type"]["hint"]


def test_readme_links_to_split_documentation():
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    for path in ("docs/commands.md", "docs/configuration.md", "docs/operation.md"):
        assert path in readme
        assert (ROOT / path).is_file()
