import json
from pathlib import Path

from core.messages import PROFILES


ROOT = Path(__file__).resolve().parents[1]
GENERATOR_LINE = "Generated by astrbot_plugin_ark_calendar·bushikq"
RENDER_TEMPLATES = (
    "calendar.html",
    "help.html",
    "history_schedule.html",
    "bilibili_dynamic.html",
    "recruitment.html",
    "recurrence.html",
)


def test_every_render_template_includes_generator_credit():
    for name in RENDER_TEMPLATES:
        assert GENERATOR_LINE in (ROOT / "templates" / name).read_text(encoding="utf-8")


def test_every_render_template_declares_utf8_before_the_encoding_prescan_limit():
    for name in RENDER_TEMPLATES:
        content = (ROOT / "templates" / name).read_bytes().lower()
        assert b'<meta charset="utf-8">' in content[:1024]
        assert b"</head>" in content


def test_recruitment_content_is_larger_than_its_title_supporting_style():
    template = (ROOT / "templates" / "recruitment.html").read_text(encoding="utf-8")
    assert ".hero h1{margin:14px 0 5px;font-size:51px}" in template
    assert ".hero p{margin:0;color:#c5d0d2;font:20px Arial" in template
    assert ".combo span{padding:6px 10px" in template
    assert "font:800 24px Arial" in template
    assert ".op{display:flex;align-items:center" in template
    assert ".op-avatar{width:54px;height:54px" in template
    assert "font-size:21px" in template
    assert 'class="recruit-rule"' in template
    assert "默认按 9 小时计算，1★、2★不计入保底" in template


def test_message_previews_cover_the_current_builtin_message_profiles():
    schema = json.loads((ROOT / "_conf_schema.json").read_text(encoding="utf-8"))
    items = schema["messages"]["items"]
    templates = items["custom_messages"]["template_schema"]
    for profile, preview_key in (("rhodes_catgirl", "rhodes_catgirl_preview"), ("plain", "plain_preview")):
        expected = "\n\n".join(
            f"【{templates[key]['name']}】\n{value}"
            for key, value in PROFILES[profile].items()
        )
        assert items[preview_key]["default"] == expected


def test_bilibili_config_order_and_video_delivery_description():
    schema = json.loads((ROOT / "_conf_schema.json").read_text(encoding="utf-8"))
    assert list(schema) == [
        "basic", "scheduled_report", "scheduled_birthday_greeting", "bilibili_dynamic",
        "cache_and_render", "messages", "admin_notification", "data_sources", "developer_mode",
    ]
    items = schema["bilibili_dynamic"]["items"]
    assert list(items) == [
        "push_enabled", "target_sid_list", "check_interval_minutes", "push_types",
        "render_image_count_threshold", "use_forward_on_qq", "list_default_count", "rsshub_base_url",
    ]
    assert "不下载或发送视频文件" in items["push_types"]["hint"]
    render_items = schema["cache_and_render"]["items"]
    assert "公招图、B站动态图和未复刻排行图" in render_items["render_device_scale_factor_level"]["hint"]
    assert "公招图、B站动态图和未复刻排行图始终使用 PNG" in render_items["render_image_type"]["hint"]


def test_unpublished_pool_display_config_defaults_to_enabled():
    schema = json.loads((ROOT / "_conf_schema.json").read_text(encoding="utf-8"))
    item = schema["basic"]["items"]["show_unpublished_pools"]
    assert item["type"] == "bool"
    assert item["default"] is True
    assert "方舟日报" in item["description"]

    assert "send_calendar_as_file" not in schema["basic"]["items"]
    developer_items = schema["developer_mode"]["items"]
    assert developer_items["enabled"]["default"] is False
    blank_height = developer_items["calendar_extra_blank_height"]
    assert blank_height["default"] == 0
    assert blank_height["condition"] == {"enabled": True}


def test_calendar_template_uses_the_developer_blank_height():
    template = (ROOT / "templates" / "calendar.html").read_text(encoding="utf-8")
    assert "calendar_extra_blank_height" in template


def test_calendar_extra_blank_height_requires_developer_mode():
    from core.renderer import CalendarRenderer

    class Service:
        def __init__(self, enabled, height):
            self.enabled = enabled
            self.height = height

        def value(self, section, key, default):
            assert (section, key, default) == ("developer_mode", "enabled", False)
            return self.enabled

        def int_value(self, section, key, default, *, minimum, maximum):
            assert (section, key, default, minimum, maximum) == (
                "developer_mode", "calendar_extra_blank_height", 0, 0, 30000
            )
            return self.height

    renderer = CalendarRenderer.__new__(CalendarRenderer)
    renderer.service = Service(False, 1200)
    assert renderer._calendar_extra_blank_height() == 0
    renderer.service = Service(True, 1200)
    assert renderer._calendar_extra_blank_height() == 1200


def test_readme_links_to_split_documentation():
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    for path in ("docs/commands.md", "docs/configuration.md", "docs/operation.md"):
        assert path in readme
        assert (ROOT / path).is_file()


def test_recruitment_easter_egg_uses_a_subtle_help_menu_note():
    from types import SimpleNamespace

    from core.help_manager import command_rows

    main = (ROOT / "main.py").read_text(encoding="utf-8")
    template = (ROOT / "templates/help.html").read_text(encoding="utf-8")

    assert 'help_note="如果参数是 all 或 *，会触发阿米娅的小彩蛋。"' in main
    assert 'class="menu-note"' in template
    assert 'color:#78848a' in template
    command = SimpleNamespace(
        name="方舟公招",
        aliases=(),
        summary="公招说明",
        help_note="如果参数是 all 或 *，会触发阿米娅的小彩蛋。",
        argument_hint="",
        example="",
    )
    assert command_rows([command])[0]["help_note"] == command.help_note
