import json
from pathlib import Path

from core.messages import PROFILES


ROOT = Path(__file__).resolve().parents[1]
GENERATOR_LINE = "Generated by astrbot_plugin_ark_calendar·bushikq"


def test_every_render_template_includes_generator_credit():
    for name in ("calendar.html", "help.html", "history_schedule.html", "bilibili_dynamic.html", "recruitment.html"):
        assert GENERATOR_LINE in (ROOT / "templates" / name).read_text(encoding="utf-8")


def test_recruitment_content_is_larger_than_its_title_supporting_style():
    template = (ROOT / "templates" / "recruitment.html").read_text(encoding="utf-8")
    assert ".hero h1{margin:14px 0 5px;font-size:51px}" in template
    assert ".hero p{margin:0;color:#c5d0d2;font:20px Arial" in template
    assert ".combo span{padding:6px 10px" in template
    assert "font:800 24px Arial" in template
    assert ".op{padding:7px 11px" in template
    assert "font-size:21px" in template


def test_message_previews_cover_the_current_builtin_message_profiles():
    schema = json.loads((ROOT / "_conf_schema.json").read_text(encoding="utf-8"))
    items = schema["messages"]["items"]
    templates = items["custom_messages"]["template_schema"]
    for profile, preview_key in (("rhodes_catgirl", "rhodes_catgirl_preview"), ("plain", "plain_preview")):
        expected = "\n\n".join(
            f"【{templates[key]['name']}】\n{value}"
            for key, value in PROFILES[profile].items()
        )
        assert items[preview_key]["default"] == expected
